[project]
name = "desafio-llm-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agents>=1.4.0",
    "faker>=37.4.2",
    "groq>=0.30.0",
    "mcp[cli]>=1.12.0",
    "sqlalchemy>=2.0.41",
    "typer>=0.16.0",
]
